### ISSUE TITLE
Demo Selected Graphing Library

### ISSUE THREAD

**Issue by dareid** [ALDLife/outcome-graph#3]
Create an adhoc demonstration of the selected graphing library (from #1) so that feedback can be received from ALD Life.

 - Show a radar chart with 10 dimensions
 - There should be 3 series of data shown on the star chart

The demonstration can just be a static data set of any format in a static HTML file. The main aim to validate the look and feel.

**Comment by themakshter** [comment]
[Demo for Chart.js](https://codepen.io/themakshter/pen/VpPGzv)

**Comment by themakshter** [comment]
Is there anything else I need to add to this one @dareid?

**Comment by dareid** [comment]
Very happy with the demo produced, closing.

**Comment by dareid** [comment]
Confirmation also received from @LydiaALDLife
