### ISSUE TITLE
Create Placeholder Interface

### ISSUE THREAD

**Issue by dareid** [ALDLife/outcome-graph#4]
Create an interface which accepts the data structure detailed within the requirements along with any other information (canvas context / DOM element for example) and produces the canned radar chart example produced in #3.

This should setup the rough structure of the module and a test example we can use going forward.

**Comment by themakshter** [comment]
The interface takes in the canvas div, a title for the graph and the sessions data. Closing this since the structure has now been added as well as a demo folder.
